version: "3.8"
services:
  backend:
    build: .
    container_name: studo-backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - studo-network
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: unless-stopped
    command: ["http", "backend:5001"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - backend
    networks:
      - studo-network
    env_file:
      - .env

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - studo-network
    env_file:
      - .env

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  studo-network:
    driver: bridge
